# Generated by Django 3.0.5 on 2020-04-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Snippets", new_name="Snippet",),
    ]
